database:
  server: "222.27.255.211:15236"
  username: "SYSDBA_TEST"
  passwd: "SYSDBA"

fileSystem:
  endpoint: "222.27.255.211:19000"
  username: "fileadmin_test"
  passwd: "fileadmin"

log:
  username: "logusers"
  passwd: "SYSDBA1234"
  CIDR: "192.168.0.0/16"
  enable: true